### ISSUE TITLE
BACK - Al guardar un nuevo producto siempre vuelve al index de productos

### ISSUE THREAD

**Issue by avozme** [josemaDAW/Proyecto-Final#39]
Al guardar un nuevo producto siempre vuelve al index de productos, aunque antes hubiéramos hecho una búsqueda o nos hubiéramos metido en una categoría.

Esto es incómodo cuando estamos editando los productos de una categoría. Lo normal en ese caso es que en el index solo viéramos los productos de esa categoría, no todos los productos de la base de datos.

**Comment by josemaDAW** [comment]
cerrado
