### ISSUE TITLE
Lupa

### ISSUE THREAD

**Issue by JuanBaronV** [josemaDAW/Proyecto-Final#46]
Es necesario añadir en los modales una lupa para ampliar las imágenes o en su defecto abrir una nueva ventana con la imagen a tamaño completo

**Comment by JuanBaronV** [comment]
Es necesario añadir en los modales una lupa para ampliar las imágenes o en su defecto abrir una nueva ventana con la imagen a tamaño completo

**Comment by avozme** [comment]
Duplicado (issue#47)
