### ISSUE TITLE
Imposible borrar ítems con datos

### ISSUE THREAD

**Issue by avozme** [josemaDAW/Proyecto-Final#59]
No se pueden borrar ítems con datos.

Me ha ocurrido al intentar eliminar un ítem duplicado por error en una categoría. Como ese ítem está asignado a algunos productos, parece que es imposible borrarlo.

La aplicación debería dejar borrarlo, aunque fuera con una advertencia severa del tipo de "Todos los datos de ese campo se perderán. Esta acción no se puede deshacer. ¿Seguro que quiere continuar?"

**Comment by JuanBaronV** [comment]
Hay que intentar forzar el error de nuevo puesto que parace que funciona correctamente

**Comment by josemaDAW** [comment]
He vuelto a probar y no ha dado error. (adolfo) Lo he probado con el item duplicado en una categoría y aún así funciona correctamente, cierro issue
