### ISSUE TITLE
BACK - Al añadir nuevo ítem se pierde la categoría en la que estaba

### ISSUE THREAD

**Issue by avozme** [josemaDAW/Proyecto-Final#62]
En la vista items/all.blade.php, se ven todos los ítems de una categoría.

Pero al pulsar el botón "Nuevo", la categoría seleccionada para el nuevo ítem no es la misma en la que estaba, sino la primera de la lista. Debería aparecer ya seleccionada la categoría en la que estaba situado.

**Comment by josemaDAW** [comment]
implementado al crear, actualizar y borrar con un         return redirect()->route('buscadorBack', ['idCategoria' => $p->categoria_id]);
