### ISSUE TITLE
La impresión de productos (generar PDF) falla a veces

### ISSUE THREAD

**Issue by avozme** [josemaDAW/Proyecto-Final#72]
La impresión de productos creados desde el panel de administración falla. Los productos creados con el seeder, en cambio, no fallan.

Este error no siempre ocurre. Hay que tratar de reproducirlo antes de corregirlo.

También se observa que ha dejado de aparecer el nombre de la categoría en los PDFs.

![image](https://user-images.githubusercontent.com/25744642/227982632-87917520-b907-40ff-ac10-986e57b62f26.png)

**Comment by josemaDAW** [comment]
Tras revision junto con adolfo hemos localizado que la impresion deja de funcionar cuando en el campo en cuestion aparece las etiquetas "<br>, &nbsp" y las palabras diacritcas se imprimen erroneamente
