### ISSUE TITLE
La página de destacados en el front no traga texto enriquecido

### ISSUE THREAD

**Issue by JuanBaronV** [josemaDAW/Proyecto-Final#78]
Al filtar en el front por el campo destacado, si algún valor contiene etiquetas como por ejemplo &nbsp o &amp, lo muestra como texto plano.

**Comment by josemaDAW** [comment]
aparte el checkbox de destacados funciona bien hasta que se edita dicho campo, en ese caso duplica la caja o la deja vacia
si filtro por tipologia y por ejemplo paso de una Tapadera a un jarron funciona bien, pero si vuelvo de jarron a tapadera lo duplica

**Comment by josemaDAW** [comment]
cuando se filtra por destacado no muestra las negritas ni cursivas directamente

**Comment by josemaDAW** [comment]
Cuando en un campo1 de un producto hay  ( &nbsp o &amp) y se esta filtrando por ese campo1 se ve en  (categorias_destacados.blade)

**Comment by AdolfoMarGar** [comment]
Solucionado con html_entity_decode antes de imprimir por pantalla
