### ISSUE TITLE
Petan destacados

### ISSUE THREAD

**Issue by JuanBaronV** [josemaDAW/Proyecto-Final#79]
Si algún valor del campo que se ha destacado está vacío peta el front.

**Comment by JuanBaronV** [comment]
A veces no funcionan de forma adecuada los destacados en el front (no agrupa y no encuentra resultados).

**Comment by josemaDAW** [comment]
Tras revision ya hemos encontrado que el error es porque se estan guardando con espacios el nombre de las fotos que lleva ese producto
