### ISSUE TITLE
Trucar textos muy largos en modal de productos

### ISSUE THREAD

**Issue by avozme** [josemaDAW/Proyecto-Final#80]
Si algun ítem tiene el texto muy largo en el modal de productos, no debería aparecer entero en el modal porque queda horrible.

Hay que truncar el texto a partir de cierta longitud (p. ej: 200 caracteres, 20 palabras, etc), y añadir un link de "Leer más". Al hacer clic en el link, el texto completo se desplegará en el modal.

**Comment by AdolfoMarGar** [comment]
Creado 2 botones, ver mas y ver menos.  Se muestran si el length del value de los items es mayor a 200
