### ISSUE TITLE
Optimizar función buscador General

### ISSUE THREAD

**Issue by JuanBaronV** [josemaDAW/Proyecto-Final#84]
Ahora mismo se está usando una función nueva (buscadoGeneral) para el buscador general del front, la función es igual que (busquedaCategorias) a excepción de la línea:
->where("productos.categoria_id", $idCategoria)
Habría que meter de alguna manera un if o un when dentro de la sentencia para optimizarla

**Comment by AdolfoMarGar** [comment]
issue duplicada
