### ISSUE TITLE
ERROR BUSCADOR GENERAL

### ISSUE THREAD

**Issue by JuanBaronV** [josemaDAW/Proyecto-Final#85]
El buscador general ha funcionado perfectamente desde siempre, lo que pasa es que los campos introducidos a mano se guardan en la base de datos con texto enriquecido, si se limpia funciona perfecto

**Comment by AdolfoMarGar** [comment]
Se ha arreglado el tema de las etiquetas con una funcion almacenada en el servidor sql, ahora hay que revisar el buscador por campos para que no se de el problema explicado en discord

**Comment by AdolfoMarGar** [comment]
ya he resuelto el problema del buscador especifico, lo unico que toma en cuenta todos los espacios generados por la funcion, me explico, al quitarle las etiquetas a <p>alfre</p><p>&nbsp;&nbsp;&nbsp; do<br></p><p> </p>, se quedaria "alfre do "
Con un espacio al final asi que si se busca "alfre do" no dara resultado
Aunque acabo de revisar, y esto solo ocurre en el buscador por campos, y en el buscador general si se busca por "alfre do" si daría resultado
Como uno esta con sql puro y el otro con elocuent digo yo que tendra que ir por aquí pero bueno
El tema de etiquetas esta resuelto ya

**Comment by AdolfoMarGar** [comment]
Todos los buscadores funcionando correctamente
